# path to LilyPond executable
lilypond_executable = /Users/paul/Library/Application Support/frescobaldi/frescobaldi/lilypond-binaries/lilypond-2.26.0/bin/lilypond
# search paths for lilypond for additional files or scripts - separate paths with | (pipe-symbol)
lilypond_search_paths = /Users/paul/Repositories/silverswan/style