plugins {
    alias(libs.plugins.openjfx.javafxplugin)
}

ecco.adapter = true

javafx {
    version = libs.versions.javafx.get()
    modules = ['javafx.base', 'javafx.controls', 'javafx.graphics']
}

dependencies {
    implementation project(':ecco-service')
    implementation libs.commonmark.core
    implementation libs.commonmark.ext.gfm.tables
}
