plugins {
    alias(libs.plugins.openjfx.javafxplugin)
}

ecco.adapter = true

javafx {
    version = libs.versions.javafx.get()
    modules = ['javafx.base', 'javafx.controls', 'javafx.graphics']
}

dependencies {
    implementation project(':ecco-service')
    implementation libs.antlr4.core
    implementation libs.antlr4.runtime
    testImplementation libs.junit4
    testImplementation libs.commons.io

}

// https://stackoverflow.com/questions/67265308/gradle-entry-classpath-is-a-duplicate-but-no-duplicate-handling-strategy-has-b
jar {
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
}
