import at.jku.isse.ecco.plugin.artifact.emf.EmfReader;
import at.jku.isse.ecco.tree.Node;
import at.jku.isse.ecco.util.Trees;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.impl.EcoreResourceFactoryImpl;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import at.jku.isse.ecco.dao.PerstEntityFactory;

import java.net.URL;
import java.util.Set;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'hhoyos' at '12/05/17 10:37' with Gradle 2.4
 *
 * @author hhoyos, @date 12/05/17 10:37
 */
public class EmfReaderTest {


    private ResourceSet rs;
    private EPackage p;

    @Before
    public void setup() {
        // FIXME We need to load the ecore and register it
        // Register Ecore because people must load their metamodels
        Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap()
                .put("ecore", new EcoreResourceFactoryImpl());
        ClassLoader classLoader = getClass().getClassLoader();
        URI uri = URI.createURI(classLoader.getResource("Library.ecore").toString());
        // FIXME this should go in the EmfReader somehow
        rs = new ResourceSetImpl();
        Resource r = rs.getResource(uri, true);
        EObject eObject = r.getContents().get(0);
        if (eObject instanceof EPackage) {
            p = (EPackage)eObject;
            //rs.getPackageRegistry().put(p.getNsURI(), p);
        }
    }

    @Test
    public void testRegisterMetamodel() {
        EmfReader reader = new EmfReader(new PerstEntityFactory(), rs);
        reader.registerMetamodel(p);
        assertTrue(reader.getResourceSet().getPackageRegistry().containsKey(p.getNsURI()));
    }
    
    @Test public void testRead() {

        EmfReader reader = new EmfReader(new PerstEntityFactory());
        ClassLoader classLoader = getClass().getClassLoader();
        URI uri = URI.createURI(classLoader.getResource("Library.xmi").toString());
        Set<Node> nodes = reader.read(new URI[]{uri});
        for (Node node : nodes) {
            Trees.print(node);
        }
        
    }

    @Test
    public void testCanRead() {
        EmfReader reader = new EmfReader(new PerstEntityFactory());
        reader.registerMetamodel(p);
        ClassLoader classLoader = getClass().getClassLoader();
        URI uri = URI.createURI(classLoader.getResource("Library.xmi").toString());
        boolean canread = reader.canRead(uri);
        assertTrue(canread);
        uri = uri.appendFileExtension(".err");
        canread = reader.canRead(uri);
        assertFalse(canread);
    }


}
