plugins {
	alias(libs.plugins.openjfx.javafxplugin)
}

ecco.adapter = true

javafx {
	version = libs.versions.javafx.get()
	modules = ['javafx.base', 'javafx.controls', 'javafx.graphics', 'javafx.swing']
}

dependencies {
	implementation project(':ecco-service')
}

ospackage {
	requires('ecco-base', version, EQUAL)
	requires('ecco-service', version, EQUAL)
}
