ecco.adapter = true

dependencies {
	implementation libs.javaparser.symbol.solver.core
	implementation libs.guava
	implementation libs.logicng.core

	implementation project(':ecco-service')

	testImplementation libs.commons.io
	testImplementation libs.commons.collections4
	testImplementation libs.log4j.api
}
