plugins {
    id 'java'
    id 'antlr'
}

ecco.adapter = true

generateGrammarSource {
    outputDirectory = new File("${project.projectDir}/src/main/java/at/jku/isse/ecco/adapter/golang/antlr".toString())
    arguments += ['-package', 'at.jku.isse.ecco.adapter.golang.antlr']
}

generateTestGrammarSource {
    outputDirectory = new File("${project.projectDir}/src/test/java/at/jku/isse/ecco/adapter/golang/antlr".toString())
    arguments += ['-package', 'at.jku.isse.ecco.adapter.golang.antlr']
}

dependencies {
    antlr libs.antlr4.core

    implementation project(':ecco-base')
    implementation project(':ecco-service')

    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testImplementation libs.mockito.core
}

test {
    testLogging {
        events "passed", "skipped", "failed"
    }
}