package at.jku.cdl.ecco.adapter.java.artifactData;

public enum ASTNodeType {
	COMPILATIONUNIT,
	IMPORT_DECLARATION,
	CATCHCLAUSE,
	UNKNOWN,
	SWITCH_STATEMENT,
	STATEMENT,
	EXPRESSION,
	SWITCH_ENTRIES,
	IF_STATEMENT, 
	FINALLY, 
	CONSTRUCTOR_DECLARATION, 
	TRYBLOCK, 
	IF_CONDITION,
	ENUM_CONSTANTS,
	BODY_DECLARATION,
	ENUM_DECLARATION,
	TYPE_DECLARATION,
	FIELD_DECLARATION,
	METHOD_DECLARATION, ELSE_BRANCH, PACKAGEDECLARATION, INITIALIZER_DECLARATION, FIELD_GROUP,
	MODULE_DECLARATION, MODULE_DIRECTIVE

}
