plugins {
    id 'java'
    alias(libs.plugins.node.gradle)
}
ecco.adapter = true
group = 'at.jku.isse.ecco'
version = '0.1.9'
npmInstall

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':ecco-service')
    // https://mvnrepository.com/artifact/com.caoccao.javet/javet
    implementation libs.javet.core
    // https://mvnrepository.com/artifact/com.caoccao.javet/javet-macos
    implementation libs.javet.macos
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testImplementation libs.junit4
}

ospackage {
    requires('ecco-base', version, EQUAL)
    requires('ecco-service', version, EQUAL)
}
node {
    download = false
    nodeProjectDir = file("${project.projectDir}/src/main/resources/script")
}
test {
    useJUnitPlatform()
}
build.dependsOn npmInstall