plugins {
	id 'org.openjfx.javafxplugin' version '0.1.0'
}

ecco.adapter = true

javafx {
	version = "21.0.4"
	modules = ['javafx.base', 'javafx.controls', 'javafx.graphics']
}

dependencies {
	implementation 'com.github.javaparser:javaparser-symbol-solver-core:3.25.8'

	implementation project(':ecco-service')
}
