plugins {
    id 'java'
}

group = 'at.jku.isse.ecco'
version = '0.1.9'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
    implementation libs.logicng.core
    implementation libs.logicng.parser.j11
}

test {
    useJUnitPlatform()
}