import at.jku.isse.ecco.plugin.emf.EmfReader;
import at.jku.isse.ecco.tree.Node;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.junit.Test;
import static org.junit.Assert.*;

import at.jku.isse.ecco.dao.PerstEntityFactory;

import java.net.URISyntaxException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Set;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'hhoyos' at '12/05/17 10:37' with Gradle 2.4
 *
 * @author hhoyos, @date 12/05/17 10:37
 */
public class EmfReaderTest {

    @Test
    public void testRegisterMetamodelFromEcore() {
        EmfReader reader = new EmfReader(new PerstEntityFactory(), new ResourceSetImpl());
        ClassLoader classLoader = getClass().getClassLoader();
        URI uri = URI.createURI(classLoader.getResource("Library.ecore").toString());
        reader.registerMetamodel(uri);
        assertTrue(reader.getResourceSet().getPackageRegistry().containsKey("http://www.eclipse.org/emf/jcrm/samples/emf/sample/Library"));
    }

    @Test
    public void testRegisterMetamodelFromEPackage() {

        ResourceSetImpl resourceSet = new ResourceSetImpl();
        EmfReader reader = new EmfReader(new PerstEntityFactory(), resourceSet);
        ClassLoader classLoader = getClass().getClassLoader();
        URI uri = URI.createURI(classLoader.getResource("Library.ecore").toString());
        Resource r = resourceSet.getResource(uri, true);
        EObject eObject = r.getContents().get(0);
        assertTrue(eObject instanceof EPackage);
        EPackage p = (EPackage)eObject;
        reader.registerMetamodel(p);
        assertTrue(reader.getResourceSet().getPackageRegistry().containsKey(p.getNsURI()));
    }

    @Test
    public void testCanRead() throws URISyntaxException {
        EmfReader reader = new EmfReader(new PerstEntityFactory(), new ResourceSetImpl());
        ClassLoader classLoader = getClass().getClassLoader();
        //URI uri = URI.createURI(classLoader.getResource("Library.xmi").toString());
        Path path = Paths.get(classLoader.getResource("Library.xmi").toURI());
        boolean canread = reader.canRead(path);
        assertTrue(canread);
        path = Paths.get(path.toString(),".err");
        canread = reader.canRead(path);
        assertFalse(canread);
    }
    
    @Test public void testRead() throws URISyntaxException {

        EmfReader reader = new EmfReader(new PerstEntityFactory(), new ResourceSetImpl());
        ClassLoader classLoader = getClass().getClassLoader();
        //URI uri = URI.createURI(classLoader.getResource("Library.xmi").toString());
        Path path = Paths.get(classLoader.getResource("Library.xmi").toURI());
        Set<Node.Op> nodes = reader.read(new Path[]{path});
        // PluginArtifact
        assertEquals(1, nodes.size());
        Node root = nodes.iterator().next();
        assertEquals(52, root.countArtifacts());
        assertEquals(1, root.getChildren().size());
        Node rn = root.getChildren().get(0);
        assertEquals(51, rn.countArtifacts());
        assertEquals(7, rn.getChildren().size());
    }
}
