name: push

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 1
      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          java-version: 17
          distribution: oracle
      - run: |
          ./gradlew build
          ./gradlew combinedjavadoc
          ./gradlew combinedWindowsZip
          ./gradlew combinedLinuxZip
          ./gradlew combinedrpm
          ./gradlew combineddeb
