name: push

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 1
      - uses: actions/setup-java@e42168ca1a833395367a6bce0db2a62f7fe4da81 # v3.11.0
        with:
          java-version: 17
          distribution: oracle
      - run: |
          ./gradlew build
          ./gradlew combinedjavadoc
          ./gradlew combinedWindowsZip
          ./gradlew combinedLinuxZip
          ./gradlew combinedrpm
          ./gradlew combineddeb
