plugins {
    id 'java'
    id 'application'
}

dependencies {
    implementation fileTree(dir: 'lib', include: '*.jar')

    implementation project(':ecco-base')
    implementation project(':ecco-service')
    implementation project(':ecco-adapter-lilypond')

}

repositories {
    mavenCentral()
}

application {

    mainClass = 'at.jku.isse.ecco.extras.RepositoryPopulationUtil'
    applicationDefaultJvmArgs = ['-Decco.headless=true']

}